#!/bin/bash

apt  update
dpkg -i ./osquery_4.5.1_1.linux.amd64.deb
cp ./rsyslog.conf /etc
systemctl restart rsyslog
cp ./osquery.conf /etc/osquery
cp ./fim.conf /usr/share/osquery/packs/
osqueryctl start
